import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"; // [locale] klasörünün içine taşıdığın için yolunu iki üst klasöre (../../) çıkacak şekilde güncelledik
import Footer from "@/components/Footer";
import Navbar from '@/components/Navbar';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "perfectcarbonrapier.com",
  description: "Generated by create next app",
};

// Next.js App Router dil parametresini (locale) otomatik olarak buraya iletir
export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // Next.js'in güncel standartlarına göre params bir Promise'dir
}) {
  const { locale } = await params;

  // Desteklediğin dillerin dışındaysa direkt 404 sayfasına yönlendir
  if (!['en', 'tr'].includes(locale)) {
    notFound();
  }

  // İlgili dilin (tr.json veya en.json) mesajlarını sunucudan getir
  const messages = await getMessages();

  return (
    <html
      lang={locale} // Sabit "en" yerine dinamik olarak gelen locale değerini yazdık
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}